"""
Generate docs/index.html from the latest squad2_output/bundle_YYYY-MM-DD.json.
Run after squad2_run.py to publish a GitHub Pages dashboard.
"""

import json
import sys
import logging
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from config import OUTPUT_DIR, DOCS_DIR

logging.basicConfig(level=logging.INFO, format="%(levelname)s — %(message)s")
log = logging.getLogger(__name__)

ACTIONS_URL = "https://github.com/subhadeep-bose/ai-media-empire/actions"

PLACEHOLDER_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Media Empire — Daily Dashboard</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: #0d1117; color: #e6edf3; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 2rem; }}
    header {{ border-bottom: 1px solid #30363d; padding-bottom: 1rem; margin-bottom: 2rem; }}
    h1 {{ color: #58a6ff; font-size: 1.8rem; }}
    .meta {{ color: #8b949e; font-size: 0.9rem; margin-top: 0.5rem; }}
    .placeholder {{ color: #8b949e; text-align: center; padding: 3rem; }}
    footer {{ margin-top: 3rem; text-align: center; color: #8b949e; font-size: 0.8rem; border-top: 1px solid #30363d; padding-top: 1rem; }}
    a {{ color: #58a6ff; }}
  </style>
</head>
<body>
  <header>
    <h1>AI Media Empire</h1>
    <p class="meta">Awaiting first pipeline run — <a href="{actions_url}">Trigger a run</a></p>
  </header>
  <div class="placeholder">
    <p>No content generated yet. The daily pipeline runs at 06:00 UTC.</p>
  </div>
  <footer>Generated by <a href="https://github.com/subhadeep-bose/ai-media-empire">AI Media Empire</a> · GitHub Actions</footer>
</body>
</html>
"""

PAGE_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Media Empire — Daily Content Dashboard</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: #0d1117; color: #e6edf3; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 2rem; }}
    header {{ border-bottom: 1px solid #30363d; padding-bottom: 1rem; margin-bottom: 2rem; }}
    h1 {{ color: #58a6ff; font-size: 1.8rem; }}
    nav {{ display: flex; gap: 1.5rem; align-items: center; margin-top: 0.75rem; flex-wrap: wrap; }}
    .meta {{ color: #8b949e; font-size: 0.9rem; }}
    .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }}
    .card h2 {{ color: #58a6ff; font-size: 1.1rem; margin-bottom: 1rem; }}
    pre {{ white-space: pre-wrap; word-break: break-word; font-size: 0.85rem; line-height: 1.6; max-height: 400px; overflow-y: auto; color: #c9d1d9; }}
    footer {{ margin-top: 3rem; text-align: center; color: #8b949e; font-size: 0.8rem; border-top: 1px solid #30363d; padding-top: 1rem; }}
    a {{ color: #58a6ff; }}
    .badge {{ display: inline-block; background: #238636; color: #fff; border-radius: 4px; padding: 2px 8px; font-size: 0.75rem; }}
  </style>
</head>
<body>
  <header>
    <h1>AI Media Empire</h1>
    <nav>
      <span class="meta">Date: {date}</span>
      <a href="{actions_url}" class="badge">Run on GitHub Actions</a>
    </nav>
  </header>
  {cards}
  <footer>Generated by <a href="https://github.com/subhadeep-bose/ai-media-empire">AI Media Empire</a> · GitHub Actions</footer>
</body>
</html>
"""


def escape_html(text: str) -> str:
    return (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
    )


def find_latest_bundle() -> Path | None:
    bundles = sorted(OUTPUT_DIR.glob("bundle_*.json"))
    return bundles[-1] if bundles else None


def build_cards(scripts: dict) -> str:
    parts = []
    for name, content in scripts.items():
        safe_content = escape_html(content)
        parts.append(
            f'  <div class="card">\n'
            f'    <h2>{escape_html(name)}</h2>\n'
            f'    <pre>{safe_content}</pre>\n'
            f'  </div>'
        )
    return "\n".join(parts)


def main():
    DOCS_DIR.mkdir(exist_ok=True)
    output_path = DOCS_DIR / "index.html"

    bundle = find_latest_bundle()
    if bundle is None:
        log.warning("No bundle found in %s — writing placeholder page", OUTPUT_DIR)
        output_path.write_text(PLACEHOLDER_HTML.format(actions_url=ACTIONS_URL), encoding="utf-8")
        log.info("Placeholder page written to %s", output_path)
        return

    log.info("Using bundle: %s", bundle)
    with open(bundle, "r", encoding="utf-8") as f:
        data = json.load(f)

    date_str = data.get("date", datetime.now().strftime("%Y-%m-%d"))
    scripts = data.get("scripts", {})

    cards_html = build_cards(scripts)
    html = PAGE_TEMPLATE.format(
        date=escape_html(date_str),
        actions_url=ACTIONS_URL,
        cards=cards_html,
    )

    output_path.write_text(html, encoding="utf-8")
    log.info("Site written to %s (%d scripts)", output_path, len(scripts))


if __name__ == "__main__":
    main()
